version: "3.9"

services:
  postgres:
    image: postgis/postgis:16-3.4       # Postgres + PostGIS
    environment:
      POSTGRES_USER: radar
      POSTGRES_PASSWORD: radar
      POSTGRES_DB: radar
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ../backend                   # путь к Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  pgdata:
