"""init hotspots & pings

Revision ID: 37e26315c7ff
Revises: 
Create Date: 2025-07-03 22:50:05.579267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '37e26315c7ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotspots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bssid', sa.String(length=17), nullable=False),
    sa.Column('ssid', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bssid')
    )
    op.execute("DROP INDEX IF EXISTS idx_hotspots_geom")
    op.create_index('idx_hotspots_geom', 'hotspots', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('pings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotspot_id', sa.Integer(), nullable=False),
    sa.Column('internet', sa.Boolean(), nullable=False),
    sa.Column('rssi', sa.SmallInteger(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pings')
    op.drop_index('idx_hotspots_geom', table_name='hotspots', postgresql_using='gist')
    op.drop_table('hotspots')
    # ### end Alembic commands ###
