name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build & start containers
      run: |
        docker compose -f infra/docker-compose.yaml up -d --build

    - name: Wait for Postgres
      run: |
        until docker compose -f infra/docker-compose.yaml exec -T postgres pg_isready -U radar ; do
          echo "⏳ waiting for db…" && sleep 2
        done

    - name: Apply migrations
      run: |
        docker compose -f infra/docker-compose.yaml exec -T backend alembic upgrade head

    - name: Run pytest
      run: docker compose -f infra/docker-compose.yaml exec -T backend \
        bash -c "cd /app && pytest -q"

    - name: Tear down
      if: always()
      run: |
        docker compose -f infra/docker-compose.yaml down -v
